### ISSUE TITLE
fix(casa): 2fa is failing to autheticate  user

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1020]
**Describe the bug**
2fa is failing to autheticate  user

**To Reproduce**
1. install flex
2. launch admin and enable otp
3. launch casa and import 2fa setting plugin "strong-authn-settings-5.0.0-12-jar-with-dependencies.jar"
4.  configure otp and enable 2fa.
5. logout and login again
6. login to casa
7. 2fa screen for otp appears
8. add otp and click on submit

**Expected behavior**
should able to login to casa

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/0f7f9678-67b8-46c6-ac45-979bc4efa3d3)

**Desktop (please complete the following information):**
  - OS: suse/ubuntu
  - Version 15 ,
  - DB mysql/pgsql
  - flex 5.0.0 nightly 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jgomer2001** [comment]
@manojs1978 please include a relevant excerpt of jans-auth_script.log and jans-auth.log 

Ensure that VM has its clock in sync with the network (Internet). If your phone and the VM have a minor difference in clock, time-based otp fails

**Comment by jgomer2001** [comment]
I'll do...

```
2023-06-26 15:22:02,115 INFO  [qtp728115831-17] 06d24fa8-29a8-4cf0-ba99-b17e68faae3e [io.jans.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Casa. getNextStep called 2

2023-06-26 15:22:33,247 ERROR [qtp728115831-17] eb460512-df45-4480-b3e7-2bec3fddf240 [jans.as.server.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:231) - com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: /
java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: /
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:222) ~[guava-32.0.0-jre.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyObject.__call__(PyObject.java:477) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyObject.__call__(PyObject.java:481) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:141) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at casa-external_otp$py.fromBase64Url$32(/opt/jans/python/libs/casa-external_otp.py:579) ~[?:?]
	at casa-external_otp$py.call_function(/opt/jans/python/libs/casa-external_otp.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyFunction.__call__(PyFunction.java:426) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:141) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at casa-external_otp$py.processOtpAuthentication$20(/opt/jans/python/libs/casa-external_otp.py:493) ~[?:?]
	at casa-external_otp$py.call_function(/opt/jans/python/libs/casa-external_otp.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyFunction.__call__(PyFunction.java:485) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:187) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at casa-external_otp$py.authenticate$9(/opt/jans/python/libs/casa-external_otp.py:189) ~[?:?]
	at casa-external_otp$py.call_function(/opt/jans/python/libs/casa-external_otp.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:187) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyFunction.__call__(PyFunction.java:449) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:171) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.pycode._pyx13.authenticate$9(casa.py:189) ~[?:?]
	at org.python.pycode._pyx13.call_function(casa.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyFunction.__call__(PyFunction.java:485) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyMethod.__call__(PyMethod.java:213) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyObject._jcallexc(PyObject.java:3565) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.core.PyObject._jcall(PyObject.java:3598) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
	at org.python.proxies.__main__$PersonAuthentication$25.authenticate(Unknown Source) ~[?:?]
	at io.jans.as.server.service.external.ExternalAuthenticationService.executeExternalAuthenticate(ExternalAuthenticationService.java:227) ~[classes/:?]
	at io.jans.as.server.service.external.ExternalAuthenticationService$Proxy$_$$_WeldClientProxy.executeExternalAuthenticate(Unknown Source) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.userAuthenticationInteractive(Authenticator.java:346) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.authenticateImpl(Authenticator.java:227) ~[classes/:?]
	at io.jans.as.server.auth.Authenticator.authenticate(Authenticator.java:139) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.el.parser.AstValue.invoke(AstValue.java:252) ~[org.mortbay.jasper.apache-el-10.0.14.jar:10.0.14]
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:266) ~[org.mortbay.jasper.apache-el-10.0.14.jar:10.0.14]
	at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) ~[weld-web-4.0.3.Final.jar:4.0.3.Final]
	at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) ~[weld-web-4.0.3.Final.jar:4.0.3.Final]
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:70) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:67) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:75) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:64) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at jakarta.faces.component.UICommand.broadcast(UICommand.java:213) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at jakarta.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:852) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at jakarta.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1329) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:56) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:681) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:437) ~[jakarta.faces-3.0.2.jar:3.0.2]
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665) ~[?:?]
	at io.jans.as.server.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:69) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at io.jans.as.server.filter.CorrelationIdFilter.doFilter(CorrelationIdFilter.java:49) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170) ~[websocket-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[?:?]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578) ~[jetty-security-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) ~[jetty-server-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381) ~[jetty-server-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[jetty-servlet-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) ~[jetty-server-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303) ~[jetty-server-11.0.15.jar:11.0.15]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[?:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[?:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[?:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[?:?]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140) ~[?:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: /
	at com.google.common.io.BaseEncoding$Alphabet.decode(BaseEncoding.java:543) ~[guava-32.0.0-jre.jar:?]
	at com.google.common.io.BaseEncoding$Base64Encoding.decodeTo(BaseEncoding.java:1044) ~[guava-32.0.0-jre.jar:?]
	at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:237) ~[guava-32.0.0-jre.jar:?]
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:220) ~[guava-32.0.0-jre.jar:?]
	... 112 more
```
