### ISSUE TITLE
fix(flex_setup): getting error while installing flex

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1372]
**Describe the bug**

**To Reproduce**
1. install flex 5.0.0-19.nightly or 5.0.0-18
2. run flex_setup.py
3. See error

**Expected behavior**
should not get any error in installation

**Screenshots**
getting error 
```Process casa: Downloading casa-external_super_gluu.py
Process casa: Downloading casa-external_twilio_sms.py
Process casa: Deploying Jetty Service
FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/flex/flex-linux-setup/flex_setup.py", line 188, in <module>
    from jans_setup import jans_setup
ImportError: cannot import name 'jans_setup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jans/jans-setup/jans_setup.py", line 445, in do_installation
    casa_installer.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 51, in start_installation
    self.render_import_templates()
  File "/opt/jans/jans-setup/setup_app/installers/casa.py", line 110, in render_import_templates
    base64_script_file = self.generate_base64_file(self.casa_script_files[0][0], 1)
  File "/opt/jans/jans-setup/setup_app/utils/crypto64.py", line 188, in generate_base64_file
    plain_file_b64encoded_text = self.reindent(plain_file_b64encoded_text, num_spaces)
  File "/opt/jans/jans-setup/setup_app/utils/setup_utils.py", line 338, in reindent
    text = text.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'


![image](https://github.com/GluuFederation/flex/assets/5729240/3e344af9-7a35-41e7-b23c-168f830223f1)

**Desktop (please complete the following information):**
  - OS: suse
  - Browser [e.g. chrome, safari]
  - Version 15 sp 4
  - DB opendj
  - flex 5.0.0-19.nightly

**Smartphone (please complete the following information):**
  - Device: [e.g. iPhone6]
  - OS: [e.g. iOS8.1]
  - Browser [e.g. stock browser, safari]
  - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by devrimyatar** [comment]
With latest changes merged and packaged, this issue is unseen
