### ISSUE TITLE
fix(admin-ui): unable to filter session

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1900]
**Describe the bug**
unable to filter session

**To Reproduce**
1. install flex 5.1.6.nightly
2. goto session in auth server
3. try to filter session 

**Expected behavior**
shold get sessions for according to filter

**Screenshots**
![image](https://github.com/user-attachments/assets/490ac862-f2ec-4eb8-8ad5-f4483d1711df)

**Desktop (please complete the following information):**
  - OS: suse 15 sp 5
-DB mysql

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manojs1978** [comment]
[log.zip](https://github.com/user-attachments/files/17901354/log.zip) config api log added

**Comment by pujavs** [comment]
@yurem , request you to please check this issue and advice. 
**Log snippet below** 
Caused by:
java.lang.NoSuchMethodError: 'org.apache.commons.lang3.Range org.apache.commons.lang3.Range.of(java.lang.Comparable, java.lang.Comparable)'
at org.apache.commons.text.translate.NumericEntityEscaper.<init>(NumericEntityEscaper.java:97)
at org.apache.commons.text.translate.NumericEntityEscaper.between(NumericEntityEscaper.java:59)
at org.apache.commons.text.StringEscapeUtils.<clinit>(StringEscapeUtils.java:270)
at io.jans.orm.sql.impl.SqlFilterConverter.convertToSqlFilterImpl(SqlFilterConverter.java:361)

**Comment by duttarnab** [comment]
Hi @mjatin-dev , please close the issue if fixed.
