### ISSUE TITLE
fix(jans): getting error in installation

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1906]
**Describe the bug**
getting error in jans_setup

**To Reproduce**
install 5.1.6.nighlty
see error

**Expected behavior**
should not get any error in installation

**Screenshots**
![image](https://github.com/user-attachments/assets/e3091705-47e4-4928-9b06-f3569e30b68d)

**Desktop (please complete the following information):**
  - OS: ubuntu22
-flex 5.1.6.nightly

**Smartphone (please complete the following information):**

**Additional context**
```
Process jans-fido2: Installing Jans-Fido2
Process jans-fido2: Deploying Jetty Service
Process jans-scim: Installing Jans-Scim
Process jans-scim: Deploying Jetty Service
Process jans-casa: Installing Jans-Casa
Process jans-casa: Deploying Jetty Service
Process jans-link: Installing Jans-Link
Process jans-link: Deploying Jetty Service
Process jans-keycloak-link: Installing Jans-Keycloak-Link
Process jans-keycloak-link: Deploying Jetty Service
Process jans-cli: Installing Jans-Cli
Process jans-cli: Installing Jans Cli
Process jans-saml: Installing Jans-Saml
Process jans-saml: Installing KC
FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/flex/flex-linux-setup/flex_setup.py", line 195, in <module>
    from jans_setup import jans_setup
ImportError: cannot import name 'jans_setup' from 'jans_setup' (/opt/jans/jans-setup/jans_setup.py)

FATAL: True
Traceback (most recent call last):
  File "/opt/jans/jans-setup/flex/flex-linux-setup/flex_setup.py", line 195, in <module>
    from jans_setup import jans_setup
ImportError: cannot import name 'jans_setup' from 'jans_setup' (/opt/jans/jans-setup/jans_setup.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jans/jans-setup/jans_setup.py", line 434, in do_installation
    jans_saml_installer.start_installation()
  File "/opt/jans/jans-setup/setup_app/installers/base.py", line 48, in start_installation
    self.service_post_setup()
  File "/opt/jans/jans-setup/setup_app/installers/jans_saml.py", line 174, in service_post_setup
    self.config_api_idp_plugin_config()
  File "/opt/jans/jans-setup/setup_app/installers/jans_saml.py", line 221, in config_api_idp_plugin_config
    self.logIt("KC did not start in 150 seconds. Giving up configuration", errorLog=True, fatal=True)
  File "/opt/jans/jans-setup/setup_app/utils/setup_utils.py", line 53, in logIt
    base.logIt(*args, **kwargs)
  File "/opt/jans/jans-setup/setup_app/utils/base.py", line 229, in logIt
    sys.exit(1)
SystemExit: 1

installation completed
```

**Comment by devrimyatar** [comment]
It was temporary
