### ISSUE TITLE
psycopg2.errors.SyntaxError: syntax error at or near "MODIFY" [SQL: ALTER TABLE "jansFido2RegistrationEntry" MODIFY COLUMN "jansCodeChallengeHash" INT]

### ISSUE THREAD

**Issue by raghumuppa** [GluuFederation/flex#328]
Hello,

Initially getting issue with the SqlDbDialect, I have generated the templates and changed the SqlDbDialect to pgsql at configmap

![image](https://user-images.githubusercontent.com/27954368/180205673-ed0296a1-ec83-42e4-9453-238d63a943ff.png)

After deploying the GLUU I'm facing an issue with Persistence Job. 

![image](https://user-images.githubusercontent.com/27954368/180204461-92b26e46-9766-406a-96a4-f12a36eda781.png)

here the issue 

```
INFO - jans.pycloudlib.wait - 2022-07-21 07:02:17,905 - Config is ready
INFO - jans.pycloudlib.wait - 2022-07-21 07:02:17,920 - Secret is ready
INFO - jans.pycloudlib.wait - 2022-07-21 07:02:18,223 - SQL is ready
INFO - sql_setup - 2022-07-21 07:02:23,797 - Creating tables (if not exist)
INFO - sql_setup - 2022-07-21 07:02:26,115 - Updating schema (if required)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "MODIFY"
LINE 1: ALTER TABLE "jansFido2RegistrationEntry" MODIFY COLUMN "jans...
                                              
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/scripts/bootstrap.py", line 39, in <module>
    main()
  File "/app/scripts/bootstrap.py", line 31, in main
    backend.initialize()
  File "/app/scripts/sql_setup.py", line 236, in initialize
    self.update_schema()
  File "/app/scripts/sql_setup.py", line 399, in update_schema
    change_column_type(mod[0], mod[1])
  File "/app/scripts/sql_setup.py", line 305, in change_column_type
    conn.execute(query)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "MODIFY"
LINE 1: ALTER TABLE "jansFido2RegistrationEntry" MODIFY COLUMN "jans...
                                                 ^

[SQL: ALTER TABLE "jansFido2RegistrationEntry" MODIFY COLUMN "jansCodeChallengeHash" INT]
(Background on this error at: http://sqlalche.me/e/13/f405)
```
Due to the above Persistence Job Failure the rest of the componenets are getting failed

![image](https://user-images.githubusercontent.com/27954368/180204939-bcf5d65f-cc92-4aa1-9004-ae748df19710.png)

and here is the values file
```
config:
  configmap:
    cnSqlDbDialect: mysql
    cnSqlDbHost: postgresxxxx.xxx
    cnSqlDbPort: 5432
    cnSqlDbName: gluu
    cnSqlDbUser: gluu
    cnSqldbUserPassword: "Nxxxxxx"
    lbAddr: "asdfsdc2.elb.me-south-1.amazonaws.com"

global:
  cnPersistenceType: sql
  fqdn: gluu-xxxxxxxx
  isFqdnRegistered: true
  nginx-ingress:
    enabled: true
  distribution: default
  storageClass:
    provisioner: kubernetes.io/aws-ebs
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer

nginx-ingress:
  ingress:
    additionalAnnotations:
      cert-manager.io/issuer: gluu-dev
    path: /
    hosts:
    - gluu-dev.xxxxx
    tls:
    - secretName: tls-certificate
      hosts:
      - gluu-devxxxxxxx
```

**Comment by moabu** [comment]
issue resolved
