### ISSUE TITLE
bug: installer-settings.volumeProvisionStrategy does not exist on tmp.yaml

### ISSUE THREAD

**Issue by rizarsyi** [GluuFederation/flex#358]
**Describe the bug**
flex-cn-setup installation failed

**To Reproduce**
1. make zipapp -> pygluu-kubernetes.pyz
2. run `./pygluu-kubernetes.pyz install`
3. after complete setup (generate-settings)
4. got error `TypeError: argument of type 'bool' is not iterable`

**Expected behavior**
`installer-settings.volumeProvisionStrategy` default value is empty string (`""`). but the key does not exist on `tmp.yaml`

**Logs**
```
2022-08-10 15:30:47,582 - gluu-common         -  INFO - Currently supported versions are : 
2022-08-10 15:30:47,582 - gluu-common         -  INFO - Stable version : 5.0
2022-08-10 15:30:47,582 - gluu-common         -  INFO - Development version : 5.0.0_dev
2022-08-10 15:30:47,584 - gluu-values-yaml     -  INFO - No Value Can Be Found for cr-rotate.image.repository
2022-08-10 15:30:47,584 - gluu-values-yaml     -  INFO - No Value Can Be Found for cr-rotate.image.tag
2022-08-10 15:30:47,825 - gluu-values-yaml     -  INFO - No Value Can Be Found for global.cr-rotate.enabled
2022-08-10 15:30:47,825 - gluu-values-yaml     -  INFO - No Value Can Be Found for config.configmap.cnPassportEnabled
2022-08-10 15:30:47,826 - gluu-values-yaml     -  INFO - No Value Can Be Found for config.configmap.cnCasaEnabled
2022-08-10 15:30:47,826 - gluu-values-yaml     -  INFO - No Value Can Be Found for config.configmap.cnCasaEnabled
2022-08-10 15:30:47,874 - gluu-values-yaml     -  INFO - No Value Can Be Found for global.istio.ingress
2022-08-10 15:30:47,874 - gluu-values-yaml     -  INFO - No Value Can Be Found for global.istio.ingress
2022-08-10 15:30:47,875 - gluu-values-yaml     -  INFO - No Value Can Be Found for global.istio.enabled
2022-08-10 15:30:47,875 - gluu-values-yaml     -  INFO - No Value Can Be Found for global.istio.namespace
2022-08-10 15:30:47,927 - gluu-values-yaml     -  INFO - No Value Can Be Found for global.cloud.testEnviroment
2022-08-10 15:30:48,404 - gluu-values-yaml     -  INFO - No Value Can Be Found for config.ldapPassword
2022-08-10 15:30:48,413 - gluu-values-yaml     -  INFO - No Value Can Be Found for config.migration.enabled
2022-08-10 15:30:48,413 - gluu-values-yaml     -  INFO - No Value Can Be Found for config.migration.enabled
2022-08-10 15:30:48,413 - gluu-prompt-config  -  INFO - You can mount your FQDN certification and key by placing them inside gluu.crt and gluu.key respectively at the same location pygluu-kubernetes.pyz is at.
2022-08-10 15:30:48,460 - gluu-values-yaml     -  INFO - No Value Can Be Found for installer-settings.images.edit
2022-08-10 15:30:48,461 - gluu-values-yaml     -  INFO - No Value Can Be Found for installer-settings.images.edit
2022-08-10 15:30:48,509 - gluu-values-yaml     -  INFO - No Value Can Be Found for config.configmap.cnPassportEnabled
2022-08-10 15:30:48,510 - gluu-values-yaml     -  INFO - No Value Can Be Found for config.configmap.cnCasaEnabled
2022-08-10 15:30:48,710 - gluu-values-yaml     -  INFO - No Value Can Be Found for installer-settings.volumeProvisionStrategy
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./pygluu-kubernetes.pyz/__main__.py", line 3, in <module>
  File "./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 247, in bootstrap
  File "./pygluu-kubernetes.pyz/_bootstrap/__init__.py", line 38, in run
  File "/home/vagrant/.shiv/pygluu-kubernetes.pyz_8156ffb83175c8a0e3181479e54fc201d32bfe272d59b9daddc4e37a283d41af/site-packages/pygluu/kubernetes/create.py", line 111, in main
    gluu = Gluu()
  File "/home/vagrant/.shiv/pygluu-kubernetes.pyz_8156ffb83175c8a0e3181479e54fc201d32bfe272d59b9daddc4e37a283d41af/site-packages/pygluu/kubernetes/gluu.py", line 29, in __init__
    if "gke" in self.settings.get("installer-settings.volumeProvisionStrategy"):
TypeError: argument of type 'bool' is not iterable
````

**System:**
  - OS: ubuntu 20.04

**Comment by moabu** [comment]
pyz removed
