### ISSUE TITLE
fix(flex-linux-setup): Installation with remote CB failing 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/flex#615]
I am trying to install Flex with remote CB. But couple of UI error messages are appearing. 
Though I see all services are loaded and active but still from UI ( Flex ) it's failing. 

```
root@testjans:/etc/jans/conf# sudo systemctl list-units --all "jans*"
  UNIT                    LOAD   ACTIVE SUB     DESCRIPTION               
  jans-auth.service       loaded active running Janssen OAauth service    
  jans-config-api.service loaded active running Janssen Config API service
  jans-fido2.service      loaded active running Janssen Fido2 Service     
  jans-scim.service       loaded active running Janssen Scim service      

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

4 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
root@testjans:/etc/jans/conf# 
```

Here is a glimpse of fido2.service which is showing that jans still looking for `jans-ldap.properties` though there is no LDAP here. I see  `jans-couchbase.properties` is available inside `/etc/jans/conf`

```
13-11 15:29:19.424 ERROR [main] [io.jans.orm.service.PersistanceFactoryService] (PersistanceFactoryService.java:96) - Unable to get Persistence Entry Manager Factory by type 'couchbase'
13-11 15:29:19.425 WARN  [main] [io.jans.orm.service.PersistanceFactoryService] (PersistanceFactoryService.java:75) - Failed to load persistence configuration. Attempting to use LDAP layer
13-11 15:29:19.427 ERROR [main] [io.jans.orm.service.PersistanceFactoryService] (PersistanceFactoryService.java:142) - Unable to load configuration file '/etc/jans/conf/jans-ldap.properties'
13-11 15:29:19.436 INFO  [main] [io.jans.fido2.service.app.ConfigurationFactory] (ConfigurationFactory.java:266) - Loading configuration from 'couchbase' DB...
13-11 15:29:19.436 INFO  [main] [io.jans.fido2.service.app.ConfigurationFactory] (ConfigurationFactory.java:266) - Loading configuration from 'couchbase' DB...
13-11 15:29:19.478 ERROR [main] [io.jans.fido2.service.app.ConfigurationFactory] (ConfigurationFactory.java:286) - null
java.lang.NullPointerException: null
    at io.jans.fido2.service.app.AppInitializer.preparePersistanceProperties(AppInitializer.java:181) ~[classes/:?]
    at io.jans.fido2.service.app.AppInitializer.createPersistenceEntryManager(AppInitializer.java:215) ~[classes/:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
    at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
    at org.jboss.weld.injection.producer.ProducerMethodProducer.produce(ProducerMethodProducer.java:103) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
    at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:161) ~[weld-core-impl-4.0.3.Final.jar:4.0.3.Final]
....
....
```

**Comment by devrimyatar** [comment]
I tested Flex Linux Setup with remote CB. I were not be able to replicate this issue.

**Comment by devrimyatar** [comment]
Re-tested. All was good.
