### ISSUE TITLE
fix(flex-linux-setup): installation fails

### ISSUE THREAD

**Issue by devrimyatar** [GluuFederation/flex#792]
**Describe the bug**
Installing on top of previously installed jans is failing:
```
Traceback (most recent call last):
  File "flex_setup.py", line 851, in <module>
    main(uninstall=argsp.remove_flex)
  File "flex_setup.py", line 827, in main
    installer_obj.install_gluu_admin_ui()
  File "flex_setup.py", line 458, in install_gluu_admin_ui
    config_api_installer.copy_tree(os.path.join(self.source_dir, 'dist'),  Config.templateRenderingDict['admin_ui_apache_root'])
  File "/root/jans_setup/setup_app/utils/setup_utils.py", line 260, in copy_tree
    shutil.copyfile(src, dest)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/root/jans_setup/flex/dist'
```

**Comment by devrimyatar** [comment]
It is user issue
