### ISSUE TITLE
fix(admin-ui): duo script showing error when enabled

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#955]
**Describe the bug**
duo script showing error when enabled

**To Reproduce**
1. install flex 5.0.0
2. login to admin
3. enable duo script
```
io.jans.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@19293be2' at io.jans.service.PythonService.loadPythonScript(PythonService.java:188) at io.jans.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source) at io.jans.service.custom.script.ExternalTypeCreator.createExternalTypeFromStringWithPythonException(ExternalTypeCreator.java:141) at io.jans.service.custom.script.ExternalTypeCreator.createExternalType(ExternalTypeCreator.java:77) at io.jans.service.custom.script.ExternalTypeCreator$Proxy$_$$_WeldClientProxy.createExternalType(Unknown Source) at io.jans.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:276) at io.jans.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:173) at io.jans.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:143) at io.jans.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:118) at io.jans.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source) at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168) at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125) at org.jboss.weld.util.Observers.notify(Observers.java:166) at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159) at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632) at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104) at io.jans.service.timer.TimerJob.execute(TimerJob.java:45) at io.jans.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:37) at org.quartz.core.JobRunShell.run(JobRunShell.java:202) at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) Caused by: File "duo.py", line 105 try: ^ SyntaxError: mismatched input '' expecting DEDENT at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95) at org.python.core.ParserFacade.parse(ParserFacade.java:190) at org.python.core.Py.compile_flags(Py.java:2249) at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297) at io.jans.service.PythonService.loadPythonScript(PythonService.java:185) ... 30 more ==================Further details============================ Failed to load python file 'java.io.ByteArrayInputStream@19293be2'

```
**Expected behavior**
should able to enable duo script without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/233997443-4a805c4a-5bd8-4ef2-a2b6-ede7dcca53d2.png)
**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 sp4
  - DB mysql
  - flex 5.0.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manojs1978** [comment]
ok thank you,
same error jans-tui as well 
moving this to jans-auth-server
[jans-auth.log](https://github.com/GluuFederation/flex/files/11319103/jans-auth.log)
[jans-auth_persistence.log](https://github.com/GluuFederation/flex/files/11319104/jans-auth_persistence.log)
[jans-auth_persistence_ldap_statistics.log](https://github.com/GluuFederation/flex/files/11319105/jans-auth_persistence_ldap_statistics.log)

**Comment by manojs1978** [comment]
moved to jans-auth
 https://github.com/JanssenProject/jans/issues/4710
