### ISSUE TITLE
fix(vm-installation) UI Backend system is down

### ISSUE THREAD

**Issue by mzico** [GluuFederation/flex#998]
After fresh installation, Admin UI not loading in Ubuntu 20 and Ubuntu 22. 
![Screenshot from 2023-05-08 00-12-42](https://user-images.githubusercontent.com/7156097/236695205-37959cac-e32d-471b-90f6-8806b9bcffbc.png)

I see below issue in `jans-config-api` startup: 

```
07-05 15:53:17.203 INFO  weld.environment.servlet.EnhancedListener EnhancedListener.java:58- WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
07-05 15:53:17.233 INFO  jboss.weld.bootstrap.WeldStartup WeldStartup.java:148- WELD-000900: 4.0.3 (Final)
07-05 15:53:17.477 INFO  validator.internal.util.Version Version.java:21- HV000001: Hibernate Validator 7.0.5.Final
07-05 15:53:17.947 INFO  environment.deployment.discovery.ReflectionDiscoveryStrategy ReflectionDiscoveryStrategy.java:49- WELD-ENV-000014: Falling back to Java Reflection for bean-discovery-mode="annotated" discovery. Add org.jboss:jandex to the classpath to speed-up startup.
07-05 15:53:18.409 INFO  jboss.weld.bootstrap.WeldStartup WeldStartup.java:236- WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
07-05 15:53:18.727 INFO  smallrye.metrics.setup.MetricCdiInjectionExtension MetricCdiInjectionExtension.java:95- SRMET01001: MicroProfile: Metrics activated (SmallRye Metrics version: 4.0.0-RC1)
07-05 15:53:18.957 INFO  jboss.weld.bootstrap.MissingDependenciesRegistry MissingDependenciesRegistry.java:46- WELD-000119: Not generating any bean definitions from io.jans.orm.couchbase.impl.CouchbaseEntryManagerFactory because of underlying class loading error: Type com.couchbase.client.java.env.ClusterEnvironment not found.  If this is unexpected, enable DEBUG logging to see the full error.
07-05 15:53:19.124 INFO  jboss.weld.bootstrap.MissingDependenciesRegistry MissingDependenciesRegistry.java:46- WELD-000119: Not generating any bean definitions from io.jans.service.MailService because of underlying class loading error: Type javax.mail.Authenticator not found.  If this is unexpected, enable DEBUG logging to see the full error.
07-05 15:53:19.852 WARN  jboss.weld.logging.ValidatorLogger ValidatorLogger.java:59- WELD-001478: Interceptor class io.jans.configapi.interceptor.AuditLogInterceptor is enabled for the application and for the bean archive /jans-config-api_/WEB-INF/classes. It will only be invoked in the @Priority part of the chain.
07-05 15:53:19.854 WARN  jboss.weld.logging.ValidatorLogger ValidatorLogger.java:59- WELD-001478: Interceptor class io.jans.configapi.interceptor.RequestReaderInterceptor is enabled for the application and for the bean archive /jans-config-api_/WEB-INF/classes. It will only be invoked in the @Priority part of the chain.
07-05 15:53:19.867 INFO  weld.environment.jetty.JettyContainer JettyContainer.java:88- WELD-ENV-001212: Jetty CdiDecoratingListener support detected, CDI injection will be available in Listeners, Servlets and Filters.
2023-05-07 15:53:21.262:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@6d167f58{jans-config-api.xml,/jans-config-api,[file:///opt/jetty-11.0/temp/jetty-localhost-8074-jans-config-api_war-_jans-config-api-any-15207995383533430157/webapp/, jar:file:///opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar!/META-INF/resources, jar:file:///opt/jetty-11.0/temp/jetty-localhost-8074-jans-config-api_war-_jans-config-api-any-15207995383533430157/webapp/WEB-INF/lib/jakarta.faces-3.0.2.jar!/META-INF/resources],UNAVAILABLE}{/opt/jans/jetty/jans-config-api/webapps/jans-config-api.war}
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type MailService with qualifiers @Default|  at injection point [UnbackedAnnotatedField] @Inject private io.jans.configapi.rest.resource.auth.ConfigSmtpResource.mailService|  at io.jans.configapi.rest.resource.auth.ConfigSmtpResource.mailService(ConfigSmtpResource.java:0)|WELD-001474: Class io.jans.service.MailService is on the classpath, but was ignored because a class it references was not found: javax.mail.Authenticator.|
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-05-07 15:53:21.285:INFO :oejs.AbstractConnector:main: Started ServerConnector@6c0c1756{HTTP/1.1, (http/1.1)}{localhost:8074}
2023-05-07 15:53:21.287:INFO :oejs.Server:main: Started Server@34b9f960{STARTING}[11.0.15,sto=5000] @12114ms
root@flex-latest:/opt/jans/jetty/jans-config-api/logs# 
```

**Comment by duttarnab** [comment]
Fixed in config-api
